from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .utils import plan_from_llm, get_user_plans, delete_plan, get_plan_by_id_and_user

# Helper function to serialize the StudyPlan object
def serialize_plan(plan):
    return {
        "id": str(plan.id),
        "user_id": str(plan.user.id),
        "title": plan.title,
        "duration": plan.duration,
        "sessions": plan.sessions, # ListField of DictField is handled automatically
        "created_at": plan.created_at,
        "updated_at": plan.updated_at,
    }

@api_view(["GET", "POST"])
@permission_classes([IsAuthenticated])
def list_and_create_plan(request):
    user = request.user
    
    if request.method == "GET":
        # GET: List all plans for the user
        plans = get_user_plans(user)
        return Response([serialize_plan(p) for p in plans])

    elif request.method == "POST":
        # POST: Create a new plan from LLM prompt
        plan_description = request.data.get("description")
        
        if not plan_description:
            return Response({"error": "Plan description is required"}, status=400)

        try:
            # Plan is generated by the LLM utility
            study_plan = plan_from_llm(user, plan_description)
            study_plan.save()
            return Response(
                {"success": True, "plan": serialize_plan(study_plan)}, 
                status=201 # HTTP 201 Created
            )
        except ValueError as e:
            return Response({"error": str(e)}, status=400)
        except Exception:
             return Response({"error": "An unexpected error occurred while creating the plan."}, status=500)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def plan_detail(request, plan_id):
    """
    GET: Retrieve the detail of a single StudyPlan.
    """
    study_plan = get_plan_by_id_and_user(request.user, plan_id)
    
    if not study_plan:
        return Response({"error": "StudyPlan not found or access denied"}, status=404)

    return Response(serialize_plan(study_plan))


@api_view(["DELETE"])
@permission_classes([IsAuthenticated])
def remove_plan(request, plan_id):
    """
    DELETE: Remove a specific StudyPlan.
    """
    try:
        ok = delete_plan(request.user, plan_id)
        if ok:
            return Response({"success": True, "message": "StudyPlan deleted successfully"}, status=204) # HTTP 204 No Content
        else:
            # Should be caught by the ValueError in delete_plan, but included for robustness
            return Response({"error": "StudyPlan not found or unauthorized"}, status=404) 
    except ValueError as e:
        return Response({"error": str(e)}, status=404)
    except Exception:
        return Response({"error": "An unexpected error occurred during deletion."}, status=500)